### ISSUE TITLE
Question: getopt-like parsing and levenshtein distance in aids::Args

### ISSUE THREAD

**Issue by JaroslawWiosna** [rexim/aids#17]
Are there any plans to add _[getopt-like](https://www.gnu.org/software/libc/manual/html_node/Example-of-Getopt.html)_  parsing to `aids::Args` ?

also would you mind levenshtein distance being move-up from [vodus_video_params.cpp](https://github.com/tsoding/vodus/blob/03c7f43a99a92f7464e009dcc6962381bcd7ebbd/src/vodus_video_params.cpp#L128) to `aids`?

---

I think I am not going to do that myself any time soon, or even at all. :-) I am just curious what is your opinion, @rexim

**Comment by rexim** [comment]
I personally don't like getopt
