### ISSUE TITLE
Bug: No compile error in Hash_Map<K, V> when there is no `hash(K)` 

### ISSUE THREAD

**Issue by JaroslawWiosna** [rexim/aids#8]
## Description

It's obvious that `hash(Key key)` is needed, if you want to create `Hash_Map<Key, Value>`. So far, only 

```c++
unsigned long hash(String_View str)
```

is implemented.

### Observed behaviour

```c++
Hash_Map<int, int> hm{}; // compiles
```
compiles, but

```c++
Hash_Map<int, int> hm{};
hm.insert(1,1); // does not compile
```
compilation error:

```console
In file included from hashes.cpp:1:0:
../aids.hpp: In instantiation of ‘void aids::Hash_Map<Key, Value>::insert(Key, Value) [with Key = int; Value = int]’:
hashes.cpp:13:22:   required from here
../aids.hpp:1127:27: error: could not convert ‘key’ from ‘int’ to ‘aids::String_View’
             auto hk = hash(key) & (capacity - 1);
                       ~~~~^~~~~
make: *** [hashes] Error 1
```

### Expected behaviour

Compilation should fail on trying to create `Hash_Map<Key, Value> hm{}` already, preferably with a meaningful message, like `hash function for argument Key is not implemented`

### Possible solutions

In https://github.com/JaroslawWiosna/aids/commit/21d2b9c402c78d8ebf615acc65b458a30d6d95e0 (branch named [hash](https://github.com/JaroslawWiosna/aids/tree/hash) )
I added:

```c++
static_assert(hash(Key{}), "hash function for argument Key is not implemented");
```
unfortunatelly it maked me add `constexpr` in 

```c++
constexpr unsigned long hash(String_View str)
```

`static_assert` would force every single `hash()` function to be constexpr, which is probably not convenient, isn't it? That is why I am filing an issue rather than pull request, willing to see your opinion about this _unexpected behaviour_ (at least it was unexpected for me)

### Additional information

Reproducible on https://github.com/rexim/aids/commit/5f2e5138a05f52189ad1508282d4d3427deba671 
My compiler:

```console
$ c++ --version
c++ (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by zhiayang** [comment]
it's possible to use SFINAE to check that the hash function exists, without forcing it to be `constexpr`: https://godbolt.org/z/hxd15E

**Comment by JaroslawWiosna** [comment]
Notes from short call on discord:

Two possible solution were presented:

1. constexpr hash() and static_assert
   - drawbacks:
     - backward incompatibility, since all off previously defined `hash()` need to be changed to `constexpr`. Also, what if somebody doesn't want to use `constexpr`?
2. SFINAE, void_t and static_assert
   - drawbacks:
     - Even though it is a nice solution, it introduced a, so called, template noise.
     - Also `void_t` type is originally [from std](https://en.cppreference.com/w/cpp/types/void_t) but the spirit of this library is not to reimplement std `one-to-one`, but rather replace `std` in simpler, `C+` way
       - Nothing wrong in `void_t`, but allowing a template noise will encourage doing so in the future

- In conclusion, the most likely solution is to _embrace the poor compiler messages_ **and close this issue without any fix**, or maybe with some comment in the source code: `Keep in mind to implement hash() and operator!= for Key`

----

- Adding a comment, gave me an idea presented in #16 which:
  1. documents the code in some sense, and
  2. utilises the *concepts mechanism*, if `__cplusplus > 201709` (`-std=c++20`)
  3. This solutions also messes up with the templates, but not really...

As discussed on discord, the power of *header-only library* allows each aids user (by aids user we mean a dev, who is capable of making changes in aids cource code) to patch it however they want, so... we already have three solutions, anyone is allowed to pick the most pleasant one :)

**Comment by rexim** [comment]
This is literally bikeshedding. We are trying to fix a fundamental flaw of C++. Something we should not waste our time on. I'm closing everything related to this.
